version: '3.7'

services:

  zookeeper:
    container_name: zookeeper
    restart: always
    # https://hub.docker.com/_/zookeeper/tags
    image: zookeeper:3.8.1
    ports:
      - '2181:2181'

  kafka:
    container_name: kafka
    restart: always
    # https://hub.docker.com/r/confluentinc/cp-kafka/tags
    image: confluentinc/cp-kafka:7.4.0
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: 'data-generator:1:1'
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
