services:

  data-generator:
    image: "ghcr.io/com.47deg/data-generator:latest"
    depends_on:
      - schema-registry
    environment:
      BOOTSTRAP_SERVERS: plaintext://broker:9093
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
    restart: always